### ISSUE TITLE
correct  "mapcan/mapcon" sample code "Lisp の map 関数" page,

### ISSUE THREAD

**Issue by yamatakau08** [tanakahx/tanakahx.github.io#1]
I found your page explains about "map" function of elisp.
http://tanakahx.github.io/blog/2014/05/18/map-function-in-lisp/
It's a nice reference for me.

But "mapcan/mapcon" section's sample code, the following doesn't work, have an error.

`
(mapcan #'list '(1 2 3) '(4 5 6))
eval: Wrong number of arguments: mapcan, 3
`

Could you correct it? I'd like to refer the correct one.
Unfortunately, I don't have much experience about elisp.

**Comment by tanakahx** [comment]
That article explains the function behavior in Common Lisp, not Emacs Lisp. Sorry to make you confused.
The specification of mapcan seems different between Common Lisp and Emacs Lisp.
Common Lisp: http://www.lispworks.com/documentation/HyperSpec/Body/f_mapc_.htm#mapcan
Emacs Lisp: https://www.gnu.org/software/emacs/manual/html_node/elisp/Mapping-Functions.html#index-mapcan-982

Common Lisp can take any number of arguments as a `&rest lists` parameter, whereas Emacs Lisp can take only one argument, `sequence`. This rule also applies to the other map* functions.

**Comment by yamatakau08** [comment]
Thank you for reply.

`That article explains the function behavior in Common Lisp, not Emacs Lisp.`

I see.
It makes me clear.
